namespace CrmCopilot.Web.Chat;

/// <summary>
/// P0-06 conversation state storage (docs/02_ARCHITECTURE.md §6). <see cref="Update"/> is the only
/// mutation path — there is deliberately no bare "get then set" pair, since that shape has a
/// read-modify-write race under concurrent requests for the same session. <paramref name="updater"/>
/// must be a pure function of the previous state: an in-memory implementation backed by
/// <see cref="System.Collections.Concurrent.ConcurrentDictionary{TKey,TValue}"/> may invoke it more
/// than once under contention.
///
/// P0-12 (WP1): every operation is keyed by <c>(userId, sessionId)</c>, not by sessionId alone.
/// sessionId is generated by the browser and never issued by the server (wwwroot/js/app.js), so a
/// sessionId-only key would let anyone who learns another user's sessionId read that user's
/// conversation context.
/// </summary>
internal interface IConversationStateStore
{
    ConversationState GetOrCreate(string userId, string sessionId);

    ConversationState Update(string userId, string sessionId, Func<ConversationState, ConversationState> updater);

    void Reset(string userId, string sessionId);
}
