namespace CrmCopilot.Contracts.Mcp;

/// <summary>generate_call_script success data (P0-10).</summary>
public sealed record GenerateCallScriptData(CallScriptDraftDto Draft);

/// <summary>
/// The RM-facing call-script draft. <see cref="RequiresHumanApproval"/> is always true,
/// server-forced — never read from the model's own output field.
///
/// The knowledge-base call scripts are playbook guidance used as evidence; this draft is generated
/// fresh and personalised per request, never a template returned verbatim (plan D5).
/// </summary>
public sealed record CallScriptDraftDto(
    string Opening,
    IReadOnlyList<string> DiscoveryQuestions,
    IReadOnlyList<string> TalkingPoints,
    IReadOnlyList<ObjectionHandlingItemDto> ObjectionHandling,
    string Closing,
    string? SuggestedProductCode,
    string? SelectedOpportunityId,
    string ResolvedObjective,
    string ObjectiveSource,
    IReadOnlyList<string> SourceIds,
    bool RequiresHumanApproval,
    IReadOnlyList<string> Warnings,
    PiiMaskSummaryDto PiiMaskSummary);

/// <summary>One anticipated objection and the grounded response to it.</summary>
public sealed record ObjectionHandlingItemDto(string Objection, string Response);

/// <summary>
/// Provenance of <see cref="CallScriptDraftDto.ResolvedObjective"/> (plan Amendment A6). Lets the
/// UI and tests tell an RM-supplied objective apart from one the tool inferred, without parsing
/// the objective text itself.
/// </summary>
public static class CallScriptObjectiveSources
{
    /// <summary>The caller supplied an explicit objective.</summary>
    public const string Request = "request";

    /// <summary>Inferred from the selected opportunity and its product.</summary>
    public const string Opportunity = "opportunity";

    /// <summary>No Open opportunity existed — periodic-care fallback.</summary>
    public const string CustomerFollowUp = "customer_follow_up";
}

/// <summary>
/// The closed vocabulary of <see cref="CallScriptDraftDto.Warnings"/> codes. These are generated by
/// the server, never by the model: model-authored warning text is only ever counted into the audit
/// log's warningCount, exactly as EmailTools already does, so free model prose cannot reach the UI
/// through this field.
/// </summary>
public static class CallScriptWarnings
{
    /// <summary>No objective was supplied; the tool derived one.</summary>
    public const string ObjectiveInferred = "OBJECTIVE_INFERRED";

    /// <summary>The periodic-care template was pinned deterministically rather than retrieved.</summary>
    public const string TemplatePinned = "TEMPLATE_PINNED";
}
